name: nightly

on:
  schedule:
    - cron:  '0 0 * * *'

  workflow_dispatch:

permissions:
  contents: none

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.21.x
      - name: Run fuzzers
        env:
          FUZZ_TIME: 30m
        run: make fuzz
