name: nightly

on:
  schedule:
    - cron:  '0 0 * * *'

  workflow_dispatch:

permissions:
  contents: none

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ^1.22.x
      - name: Run fuzzers
        env:
          FUZZ_TIME: 30m
        run: make fuzz
