name: weekly

on:
  schedule:
    - cron:  '0 0 * * 0'

  workflow_dispatch:

permissions:
  contents: none

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
      - name: Run fuzzers
        env:
          # Each fuzz target is run for this long in turn.
          FUZZ_TIME: 20m
        run: make fuzz
